Kaizen_final/Controllers/FarmersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Kaizen_final.Data;
using Kaizen_final.Models;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace Kaizen_final.Controllers
{
    [Authorize(Roles = "Admin,Employee")]
    public class FarmersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public FarmersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Farmers
        public async Task<IActionResult> Index()
        {
            return View(await _context.Farmers.ToListAsync());
        }

        [Authorize(Roles = "Admin,Employee")]
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var farmer = await _context.Farmers
                .FirstOrDefaultAsync(m => m.farmerId == id);
            if (farmer == null)
            {
                return NotFound();
            }

            return View(farmer);
        }

        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("farmerId,farmerName,farmerEmail,farmerPhoneNumber")] Farmer farmer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(farmer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(farmer);
        }

        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var farmer = await _context.Farmers.FindAsync(id);
            if (farmer == null)
            {
                return NotFound();
            }
            return View(farmer);
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("farmerId,farmerName,farmerEmail,farmerPhoneNumber")] Farmer farmer)
        {
            if (id != farmer.farmerId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(farmer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FarmerExists(farmer.farmerId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(farmer);
        }


        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var farmer = await _context.Farmers
                .FirstOrDefaultAsync(m => m.farmerId == id);
            if (farmer == null)
            {
                return NotFound();
            }

            return View(farmer);
        }

        // POST: Farmers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var farmer = await _context.Farmers.FindAsync(id);
            _context.Farmers.Remove(farmer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FarmerExists(int id)
        {
            return _context.Farmers.Any(e => e.farmerId == id);
        }
    }
}

Kaizen_final/Controllers/TeasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Kaizen_final.Data;
using Kaizen_final.Models;
using Microsoft.AspNetCore.Authorization;

namespace Kaizen_final.Controllers
{
    [Authorize]
    // //  var roles = new[] { "Admin", "Manager", "Employee" };

    public class TeasController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TeasController(ApplicationDbContext context)
        {
            _context = context;
        }


        [Authorize(Roles = "Admin,Employee")]
        public async Task<IActionResult> farmersearch(string farmersearch)
        {
            var applicationDbContext = from f in _context.Teas.Include(t => t.Farmer)
                                       select f;

            if (!String.IsNullOrEmpty(farmersearch))
            {
                applicationDbContext = applicationDbContext.Where(f => f.Farmer.farmerName.Contains(farmersearch));
            }

            return View(await applicationDbContext.ToListAsync());
        }

        public async Task<IActionResult> Index(string searchString)
        {
            //var applicationDbContext = _context.Teas.Include(t => t.Farmer);
            //return View(await applicationDbContext.ToListAsync());
            var searchFarmer = from m in _context.Teas
                               select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                searchFarmer = searchFarmer.Where(s => s.TeaName.Contains(searchString));
            }

            return View(await searchFarmer.ToListAsync());

        }

        
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tea = await _context.Teas
                .Include(t => t.Farmer)
                .FirstOrDefaultAsync(m => m.TeaId == id);
            if (tea == null)
            {
                return NotFound();
            }

            return View(tea);
        }

        //  var roles = new[] { "Admin", "Manager", "Employee" };

        [Authorize(Roles = "Admin,Employee")]
        public IActionResult Create()
        {
            ViewData["farmerid"] = new SelectList(_context.Farmers, "farmerId", "farmerId");
            return View();
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TeaId,TeaName,TeaDescription,Price,Tea_Stock,picURL,farmerid")] Tea tea)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tea);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["farmerid"] = new SelectList(_context.Farmers, "farmerId", "farmerId", tea.farmerid);
            return View(tea);
        }

        [Authorize(Roles = "Admin,Employee")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tea = await _context.Teas.FindAsync(id);
            if (tea == null)
            {
                return NotFound();
            }
            ViewData["farmerid"] = new SelectList(_context.Farmers, "farmerId", "farmerId", tea.farmerid);
            return View(tea);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TeaId,TeaName,TeaDescription,Price,Tea_Stock,picURL,farmerid")] Tea tea)
        {
            if (id != tea.TeaId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tea);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TeaExists(tea.TeaId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["farmerid"] = new SelectList(_context.Farmers, "farmerId", "farmerId", tea.farmerid);
            return View(tea);
        }


        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tea = await _context.Teas
                .Include(t => t.Farmer)
                .FirstOrDefaultAsync(m => m.TeaId == id);
            if (tea == null)
            {
                return NotFound();
            }

            return View(tea);
        }

        // POST: Teas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tea = await _context.Teas.FindAsync(id);
            _context.Teas.Remove(tea);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TeaExists(int id)
        {
            return _context.Teas.Any(e => e.TeaId == id);
        }
    }
}

Kaizen_final/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>

   
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="icon" type="image/x-icon" href="~/images/tea1.ico">

    <title>@ViewData["Title"] -  &nbsp;&nbsp;Kaizen</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link rel="stylesheet" href="~/css/mycss.css"/>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <img src="~/images/logo.png" style="width:60px;height:50px;" />
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Kaizen</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">About us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Farmers" asp-action="Index">Farmer</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teas" asp-action="Index">Teas</a>
                        </li>
                        <li class="nav-item">
                            @*<img src="~/images/logo.png" style="width:10px;height:5px;" />*@
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teas" asp-action="farmersearch">FarmerSearch</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Kaizen - @*<a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>*@
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    @*<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>*@
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" crossorigin="anonymous"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>